### ISSUE TITLE
Choose other language

### ISSUE THREAD

**Issue by juanmanuel-calderon** [va1erian/isuucc#2]
plz

**Comment by va1erian** [comment]
RUST IS ALL I HAVE NOW

**Comment by kernevez** [comment]
Can we maybe rediscuss this issue ?

I saw a small project in Java/OSGi and it's BLAZING FAST.

**Comment by va1erian** [comment]
NO.

**Comment by kernevez** [comment]
What about now?

**Comment by Kernevez-A** [comment]
Please reconsider
